# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2
pipelines:
  # default - contains the steps that will run on every push.
  # default:
  branches:
   # You can include your custom branches and the steps you'd like to undertake e.g. testing
   #staging:
   master:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - cd application
          - composer install
          - cd ../
    - step:
       name: Deploy to production one
       deployment: production
       script:
         - pipe: atlassian/ssh-run:0.2.2
           variables:
             SSH_USER: 'customer'
             SERVER: '173.208.146.82'
             COMMAND: 'cd /var/www/payhere-api-docs && git pull origin master && ./deploy.sh'